### PR TITLE
Fixed prevent sending emails for support user

### LINKED ISSUE #1136: Prevent sending invite SMS and email when creating support user

### PR DESCRIPTION
**Pull request by paulsojan**
Fixes #1136

### CODE REVIEW

File: app/mailers/user_mailer.rb [hunk 1]
```diff
@@ -21,7 +23,7 @@ def course_deadline_reminder(user, course, deadline)
     @course = course
     @deadline = deadline.to_fs(:short)
 
-    return if @user.email.blank?
+    return if @user.email.blank? || email_disabled_for?(@user)
```
Comment (deepakkumarnd) [inline app/mailers/user_mailer.rb]: @user.email.blank? can be moved to the email_disabled_for? function
